{
  config,
  modulesPath,
  pkgs,
  lib,
  ...
}: {
  # system mounts
  # These settings match the image file generated by the NixOS Lima VM image generator
  boot.loader.grub = {
    device = "nodev";
    efiSupport = true;
    efiInstallAsRemovable = true;
  };

  fileSystems."/boot" = {
    device = lib.mkForce "/dev/vda1"; # /dev/disk/by-label/ESP
    fsType = "vfat";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    autoResize = true;
    fsType = "ext4";
    options = ["noatime" "nodiratime" "discard"];
  };

  boot.kernelPackages = pkgs.linuxPackages_latest;
}
