#!/usr/bin/env bash

set -euo pipefail

pushd ~/dotfiles
nix build .#darwinConfigurations.DarioAir.system
brew trust --taps cloudflare/cloudflare
brew trust --formulae cloudflare/cloudflare/cf-terraforming
nh darwin switch --show-activation-logs --print-build-logs .
popd
